const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const names=['梅瓶','玉壶春','葫芦瓶','手作瓶'];
const profiles=[[.39,.40,.39,.43,.50,.58,.65,.70,.72,.70,.59,.40,.24,.25],[.31,.36,.43,.55,.64,.66,.59,.47,.33,.23,.21,.23,.29,.34],[.33,.39,.51,.62,.65,.55,.38,.28,.32,.44,.47,.41,.27,.25],[.37,.40,.30,.39,.76,.62,.35,.32,.47,.73,.73,.49,.34,.35]];
let state={step:0,shape:0,color:-1,hue:175,seed:Math.random()*100,stamp:'入窑万彩',style:0,profile:[...profiles[0]]}, spinning=false, firing=false;
let saved=[];try{saved=JSON.parse(localStorage.getItem('ruyao-works')||'[]')}catch{}
const scene=new THREE.Scene(), camera=new THREE.PerspectiveCamera(31,1,.1,100);camera.position.set(0,1.62,7.5);camera.lookAt(0,1.48,0);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0,0);renderer.outputEncoding=THREE.sRGBEncoding;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;$('#scene').appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xffffff,0xb1ac96,1.5));const key=new THREE.DirectionalLight(0xfffaf0,2.3);key.position.set(-3,5,4);scene.add(key);const fill=new THREE.DirectionalLight(0xeafaff,.8);fill.position.set(4,2,-2);scene.add(fill);
const envScene=new THREE.Scene();envScene.background=new THREE.Color('#b8b9b1');for(const [x,y,z,w,h,power] of [[-3,3,3,2,4,3],[3,2,2,.7,3,2],[0,5,0,5,2,2]]){let m=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({color:new THREE.Color(power,power,power)}));m.position.set(x,y,z);m.lookAt(0,1,0);envScene.add(m)}const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(envScene).texture;
const material=new THREE.MeshPhysicalMaterial({color:0xe7e3d8,roughness:.7,metalness:0,clearcoat:.13,clearcoatRoughness:.22,side:THREE.DoubleSide});const pot=new THREE.Mesh(new THREE.BufferGeometry(),material);scene.add(pot);
const shadowCanvas=document.createElement('canvas');shadowCanvas.width=128;shadowCanvas.height=128;let sc=shadowCanvas.getContext('2d'),g=sc.createRadialGradient(64,64,1,64,64,64);g.addColorStop(0,'rgba(115,98,64,.3)');g.addColorStop(1,'rgba(115,98,64,0)');sc.fillStyle=g;sc.fillRect(0,0,128,128);let shadow=new THREE.Mesh(new THREE.PlaneGeometry(3.9,2.3),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(shadowCanvas),transparent:true,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.y=-.035;scene.add(shadow);
function radius(t){let k=t*(state.profile.length-1),i=Math.floor(k),f=k-i,p=state.profile;let a=p[Math.max(0,i-1)],b=p[i],c=p[Math.min(i+1,p.length-1)],d=p[Math.min(i+2,p.length-1)];return .5*((2*b)+(-a+c)*f+(2*a-5*b+4*c-d)*f*f+(-a+3*b-3*c+d)*f*f*f)}
function rebuild(){let points=[new THREE.Vector2(0,0),new THREE.Vector2(state.profile[0]*.97,0)];for(let i=0;i<=130;i++)points.push(new THREE.Vector2(radius(i/130),i/130*2.8+.025));let r=radius(1);points.push(new THREE.Vector2(r-.006,2.838),new THREE.Vector2(r-.04,2.838));for(let i=130;i>=110;i--)points.push(new THREE.Vector2(Math.max(.04,radius(i/130)-.045),i/130*2.8+.025));points.push(new THREE.Vector2(0,2.36));pot.geometry.dispose();pot.geometry=new THREE.LatheGeometry(points,128);pot.geometry.computeVertexNormals()}
function hash(x,y){let n=Math.sin(x*127.1+y*311.7+state.seed)*43758.5453;return n-Math.floor(n)}function noise(x,y){let i=Math.floor(x),j=Math.floor(y),u=x-i,v=y-j;u=u*u*(3-2*u);v=v*v*(3-2*v);return hash(i,j)*(1-u)*(1-v)+hash(i+1,j)*u*(1-v)+hash(i,j+1)*(1-u)*v+hash(i+1,j+1)*u*v}function fbm(x,y){return noise(x,y)*.55+noise(x*2,y*2)*.27+noise(x*4,y*4)*.12+noise(x*9,y*9)*.06}
const palettes=[['#3c9390','#a4d9c2','#c5d6b4'],['#164b9b','#78abc3','#d5ddbb'],['#853329','#bd7770','#d4c5ab'],['#577e65','#9bbb95','#d7d5ad'],['#567b9a','#ca999b','#d5d9bd'],['#663e79','#b08cba','#c5cdc3']];
function glaze(baked=false,custom=false){if(state.color<0){material.map?.dispose();material.map=null;material.color.set('#e5e1d7');material.roughness=.72;material.clearcoat=.1;material.needsUpdate=true;return}const c=document.createElement('canvas');c.width=512;c.height=1024;let ctx=c.getContext('2d'),img=ctx.createImageData(c.width,c.height);let colors=palettes[state.color].map(c=>new THREE.Color(c));if(custom){colors=[new THREE.Color().setHSL(state.hue/360,.38,.4),new THREE.Color().setHSL(state.hue/360,.35,.7),new THREE.Color('#d7ddbd')]}
for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++){let n=fbm(x/90,y/125),flow=fbm(x/45,y/210);let v=baked?Math.max(0,Math.min(1,(n-.37)*3.7)):Math.max(0,Math.min(1,(n-.3)*1.5));let a=colors[0],b=colors[1],r=a.r*(1-v)+b.r*v,gg=a.g*(1-v)+b.g*v,bb=a.b*(1-v)+b.b*v;if(baked&&n>.62){let m=Math.min(1,(n-.62)*7);r=r*(1-m)+colors[2].r*m;gg=gg*(1-m)+colors[2].g*m;bb=bb*(1-m)+colors[2].b*m}if(y>970+(flow-.5)*55&&baked){r=.7;gg=.66;bb=.48}let grain=(hash(x,y)-.5)*.022;let i=(y*c.width+x)*4;img.data[i]=(r+grain)*255;img.data[i+1]=(gg+grain)*255;img.data[i+2]=(bb+grain)*255;img.data[i+3]=255}ctx.putImageData(img,0,0);
if(baked){ctx.strokeStyle='rgba(84,73,46,.12)';ctx.lineWidth=.55;for(let i=0;i<85;i++){let x=hash(i,4)*512,y=hash(i,8)*1024;ctx.beginPath();ctx.moveTo(x,y);for(let j=0;j<5;j++){x+=(hash(i,j+50)-.5)*55;y+=hash(i,j+80)*32;ctx.lineTo(x,y)}ctx.stroke()}}material.map?.dispose();material.map=new THREE.CanvasTexture(c);material.map.encoding=THREE.sRGBEncoding;material.color.set('#ffffff');material.roughness=baked?.2:.31;material.clearcoat=baked?1:.6;material.clearcoatRoughness=.13;material.needsUpdate=true}
function resize(){let el=$('#scene');renderer.setSize(el.clientWidth,el.clientHeight);camera.aspect=el.clientWidth/el.clientHeight;camera.position.z=camera.aspect<.8?7.1:6.6;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe($('#scene'));
function step(n){state.step=n;$('#app').classList.toggle('finished',n===5);$('#scene').hidden=n===2;$('.brand').hidden=n===2;$('#side').hidden=n>=2;$('#controls').hidden=n===2||n===5;for(const [id,s] of [['shapePanel',0],['glazePanel',1],['stampPanel',2],['firePanel',3],['firingPanel',4],['result',5],['resultActions',5]])$('#'+id).hidden=n!==s;if(n===5){$('#resultTitle').textContent='窑变釉 · '+names[state.shape];$('.resultSeal').textContent=state.stamp;$('.resultSeal').classList.toggle('outline',state.style===1)}requestAnimationFrame(resize)}
$$('[data-shape]').forEach(b=>b.onclick=()=>{state.shape=+b.dataset.shape;state.profile=[...profiles[state.shape]];$$('[data-shape]').forEach(x=>x.classList.toggle('selected',x===b));$('#shapeHint').textContent=state.shape===3?'在器身上左右拖动 · 随心塑形':'经典器形 · 选定后上釉';rebuild()});
$$('[data-color]').forEach(b=>b.onclick=()=>{state.color=+b.dataset.color;$$('[data-color]').forEach(x=>x.classList.toggle('selected',x===b));glaze()});$('#hue').oninput=e=>{state.hue=+e.target.value;if(state.color<0)state.color=0;glaze(false,true)};
$('#toGlaze').onclick=()=>step(1);$('#toStamp').onclick=()=>{if(state.color<0){state.color=0;glaze()}step(2)};$('#stampInput').oninput=e=>{state.stamp=e.target.value.trim()||'入窑万彩';$('.stampPreview').textContent=state.stamp};$$('[data-style]').forEach(b=>b.onclick=()=>{state.style=+b.dataset.style;$$('[data-style]').forEach(x=>x.classList.toggle('selected',x===b));$('.stampPreview').classList.toggle('outline',!!state.style)});$('#stampNext').onclick=()=>step(3);
function toast(s){$('#toast').textContent=s;$('#toast').style.opacity=1;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.opacity=0,2400)}
$('#back').onclick=()=>{if(firing)return;if(state.step>0)step(state.step===5?3:state.step-1);else toast('选择器形，开启你的陶艺创作')};$('#reset').onclick=()=>{state.color=-1;glaze();$$('[data-color]').forEach(b=>b.classList.remove('selected'));toast('釉色已清除')};
$('#fire').onclick=()=>{if(firing)return;firing=true;step(4);spinning=true;$('#fireText').textContent='入 窑 ···';setTimeout(()=>{key.color.set('#ffd6a0');$('#fireText').textContent='窑 火 正 盛 ···'},1000);setTimeout(()=>{glaze(true);key.color.set('#fffaf0');$('#fireText').textContent='出 窑 ···'},2700);setTimeout(()=>{firing=false;spinning=false;step(5);requestAnimationFrame(()=>{renderer.render(scene,camera);const record={...state,profile:[...state.profile],id:Date.now(),image:renderer.domElement.toDataURL('image/png')};saved.unshift(record);saved=saved.slice(0,12);try{localStorage.setItem('ruyao-works',JSON.stringify(saved))}catch{toast('作品已生成；浏览器存储不足，请保存图片')}})},4300)};
let drag=null;renderer.domElement.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,moved:false};renderer.domElement.setPointerCapture(e.pointerId)});renderer.domElement.addEventListener('pointermove',e=>{if(!drag||firing)return;let dx=e.clientX-drag.x;drag.moved=drag.moved||Math.abs(dx)>2;if(state.step===0){let rect=renderer.domElement.getBoundingClientRect(),t=1-(e.clientY-rect.top)/rect.height;t=Math.max(0,Math.min(1,(t-.1)/.8));let at=t*(state.profile.length-1);state.profile=state.profile.map((r,i)=>Math.max(.13,Math.min(.88,r+dx*.003*Math.exp(-Math.pow((i-at)/1.1,2)))));state.shape=3;$$('[data-shape]').forEach(x=>x.classList.toggle('selected',x.dataset.shape==='3'));rebuild()}else pot.rotation.y+=dx*.012;drag.x=e.clientX});renderer.domElement.addEventListener('pointerup',()=>{if(drag&&!drag.moved&&state.step===1&&state.color>=0){state.seed+=1;glaze()}drag=null});renderer.domElement.addEventListener('pointercancel',()=>drag=null);
$('#rotate').onclick=()=>{spinning=!spinning;$('#rotate').firstChild.textContent=spinning?'Ⅱ':'▷'};$('#again').onclick=()=>{state.profile=[...profiles[0]];state.shape=0;state.color=-1;state.seed=Math.random()*100;spinning=false;pot.rotation.y=0;rebuild();glaze();$$('[data-shape]').forEach(x=>x.classList.toggle('selected',x.dataset.shape==='0'));$$('[data-color]').forEach(x=>x.classList.remove('selected'));step(0)};
function gallery(){let el=$('#galleryItems');el.replaceChildren();if(!saved.length){let p=document.createElement('p');p.textContent='博古架尚空，烧制第一件作品吧。';el.append(p)}saved.forEach(item=>{let b=document.createElement('button'),im=document.createElement('img');im.src=item.image;im.alt=names[item.shape];b.append(im,document.createTextNode(item.stamp+' · '+names[item.shape]));b.onclick=()=>{state={...item,profile:[...item.profile]};rebuild();glaze(true);spinning=false;step(5);$('#gallery').close()};el.append(b)});$('#gallery').showModal()}$('#shelf').onclick=$('#collection').onclick=$('#history').onclick=gallery;$('.close').onclick=()=>$('#gallery').close();
function exportImage(){renderer.render(scene,camera);let c=document.createElement('canvas');c.width=1200;c.height=1800;let x=c.getContext('2d');x.fillStyle='#eef0e7';x.fillRect(0,0,1200,1800);x.strokeStyle='#b7bdaf';x.lineWidth=2;x.strokeRect(50,50,1100,1700);x.drawImage(renderer.domElement,200,140,800,1120);x.fillStyle='#36453d';x.font='64px KaiTi,serif';['入','窑','万','彩'].forEach((t,i)=>x.fillText(t,115,190+i*76));x.font='20px serif';x.fillText('入窑一色 · 出窑万彩',110,560);x.textAlign='center';x.strokeStyle='#c2c8ba';x.beginPath();x.moveTo(260,1330);x.lineTo(940,1330);x.stroke();x.font='46px KaiTi,serif';x.fillText('窑变釉 · '+names[state.shape],600,1430);x.font='23px serif';x.fillStyle='#8b9285';x.fillText('柴窑烧成 · 丙午年孟秋 · 孤品不可复烧',600,1490);x.strokeStyle='#aa4132';x.strokeRect(550,1550,100,100);x.fillStyle='#aa4132';x.font='32px KaiTi,serif';let chars=[...state.stamp];chars.forEach((t,i)=>x.fillText(t,chars.length>2?575+(i%2)*50:600,1590+(chars.length>2?Math.floor(i/2):i)*40));return c.toDataURL('image/png')}
$('#save').onclick=()=>{let a=document.createElement('a');a.download='入窑万彩-'+names[state.shape]+'.png';a.href=exportImage();a.click();toast('作品海报已导出')};$('#share').onclick=()=>{if(state.step===5)$('#save').click();else toast('完成烧制后，即可导出作品分享')};$('#note').onclick=async()=>{let text='入窑一色，出窑万彩。\n我的「'+names[state.shape]+'」，底款「'+state.stamp+'」。\n泥土与火，留下独一无二的窑变。';try{await navigator.clipboard.writeText(text);toast('作品文案已复制')}catch{toast(text)}};
rebuild();glaze();resize();let last=0;function animate(t){requestAnimationFrame(animate);if(spinning)pot.rotation.y+=Math.min((t-last)/1000,.05)*.5;last=t;renderer.render(scene,camera)}requestAnimationFrame(animate);window.ruyao={get state(){return state},get saved(){return saved},renderer,pot,exportImage};
